command:
  HealCommand:
    name: "heal"
    aliases: ""
  FeedCommand:
    name: "feed"
    aliases: ""
  GameModeCommand:
    name: "gamemode"
    aliases: "gm"

# lista blokowanych komend
blockedCommands:
  - "bukkit"